/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElInput: typeof import('element-plus/es').ElInput
  const ElMess: typeof import('element-plus/es').ElMess
  const ElMessage: typeof import('element-plus/es').ElMessage
}
