/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedSelect: typeof import('./src/components/AnimatedSelect/index.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker/index.vue')['default']
    DraggableDialog: typeof import('./src/components/DraggableDialog/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ModelLoader: typeof import('./src/components/ModelLoader/index.vue')['default']
    ModelPropDialog: typeof import('./src/components/ModelPropDialog/index.vue')['default']
    NextLoading: typeof import('./src/components/NextLoading/index.vue')['default']
    RadialMenu: typeof import('./src/components/RadialMenu/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionDialog: typeof import('./src/components/SectionDialog/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar/index.vue')['default']
  }
}
